export const APPROVED_PHRASE_BANK = [
  {
    id: 'obs_compact_order_01',
    section: 'observation',
    relation: 'sequence',
    requiredClaims: [],
    blockedClaims: ['interpretation'],
    pattern: '{topic} {firstAction}.',
    tone: 'teacher_record',
    length: 'short',
    qualityTags: ['natural', 'safe', 'objective'],
  },
  {
    id: 'obs_two_step_01',
    section: 'observation',
    relation: 'sequence',
    requiredClaims: [],
    blockedClaims: ['interpretation'],
    pattern: '{topic} {firstAction}. 이후 {secondAction}.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['ordered', 'safe'],
  },
  {
    id: 'obs_speech_01',
    section: 'observation',
    relation: 'action_to_expression',
    requiredClaims: ['speech'],
    blockedClaims: ['speech_rewrite'],
    pattern: '{topic} {firstAction}. 이 과정에서 {speechText}.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['speech_preserved', 'safe'],
  },
  {
    id: 'retry_after_setback_01',
    section: 'learning',
    relation: 'retry_after_setback',
    themes: ['retry'],
    requiredClaims: ['retry'],
    blockedClaims: ['confidence_growth', 'ability_growth'],
    pattern: '{topic} 뜻대로 되지 않는 상황에서도 {focusActionConnector} 놀이를 이어 갔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['natural', 'specific', 'safe'],
  },
  {
    id: 'retry_after_setback_02',
    section: 'learning',
    relation: 'retry_after_setback',
    themes: ['retry'],
    requiredClaims: ['retry'],
    blockedClaims: ['problem_solving_growth'],
    pattern: '{topic} {focusProcess} 방법을 바꾸어 시도를 이어 갔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['process', 'safe'],
  },
  {
    id: 'explore_change_01',
    section: 'learning',
    relation: 'action_to_material_exploration',
    themes: ['change_explore', 'question'],
    requiredClaims: ['explore'],
    blockedClaims: ['understanding_principle'],
    pattern: '{topic} {focusProcess} 대상의 특징과 변화를 살펴보았다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['natural', 'specific', 'safe'],
  },
  {
    id: 'make_construct_01',
    section: 'learning',
    relation: 'action_to_material_exploration',
    themes: ['make'],
    requiredClaims: ['make'],
    blockedClaims: ['creativity_growth'],
    pattern: '{topic} 재료를 다루며 형태를 구성해 보았다.',
    tone: 'teacher_record',
    length: 'short',
    qualityTags: ['natural', 'safe'],
  },
  {
    id: 'language_speech_01',
    section: 'learning',
    relation: 'action_to_expression',
    themes: ['language', 'question', 'story'],
    requiredClaims: ['speech'],
    blockedClaims: ['language_growth'],
    pattern: '{topic} 말로 생각이나 경험을 전하며 놀이 흐름을 이어 갔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['speech', 'safe'],
  },
  {
    id: 'roleplay_flow_01',
    section: 'learning',
    relation: 'sequence',
    themes: ['roleplay', 'story'],
    requiredClaims: ['roleplay'],
    blockedClaims: ['imagination_growth'],
    pattern: '{topic} 역할에 맞는 말과 행동으로 놀이 장면을 이어 갔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['natural', 'safe'],
  },
  {
    id: 'peer_share_01',
    section: 'learning',
    relation: 'action_to_peer_interaction',
    themes: ['peer_share', 'peer_help'],
    requiredClaims: ['peer'],
    blockedClaims: ['social_development'],
    pattern: '{topic} 친구와 함께하는 흐름 안에서 차례와 역할을 경험했다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['peer', 'safe'],
  },
  {
    id: 'conflict_adjust_01',
    section: 'learning',
    relation: 'conflict_to_apology',
    themes: ['conflict'],
    requiredClaims: ['conflict'],
    blockedClaims: ['conflict_resolved'],
    pattern: '{topic} 갈등 상황에서 말이나 행동으로 상황을 조정해 보았다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['safe', 'objective'],
  },
  {
    id: 'rules_turn_01',
    section: 'learning',
    relation: 'action_to_peer_interaction',
    themes: ['rules'],
    requiredClaims: ['turn_waiting'],
    blockedClaims: ['rule_obedience'],
    pattern: '{topic} 차례와 순서를 확인하며 놀이 흐름을 이어 갔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['natural', 'safe'],
  },
  {
    id: 'selfhelp_daily_01',
    section: 'learning',
    relation: 'action_to_self_care',
    themes: ['selfhelp'],
    requiredClaims: ['self_care'],
    blockedClaims: ['independence_complete'],
    pattern: '{topic} 일상에서 필요한 행동을 스스로 해 보았다.',
    tone: 'teacher_record',
    length: 'short',
    qualityTags: ['natural', 'safe'],
  },
  {
    id: 'movement_control_01',
    section: 'learning',
    relation: 'single_event',
    themes: ['movement'],
    requiredClaims: ['movement'],
    blockedClaims: ['motor_development'],
    pattern: '{topic} 몸의 움직임과 방향을 조절해 보았다.',
    tone: 'teacher_record',
    length: 'short',
    qualityTags: ['natural', 'safe'],
  },
  {
    id: 'emotion_expression_01',
    section: 'learning',
    relation: 'single_event',
    themes: ['emotion_expression'],
    requiredClaims: ['emotion_expression'],
    blockedClaims: ['emotion_regulation', 'recovery'],
    pattern: '{topic} 관찰된 말과 행동으로 마음을 표현했다.',
    tone: 'teacher_record',
    length: 'short',
    qualityTags: ['safe', 'objective'],
  },
  {
    id: 'emotion_recovery_01',
    section: 'learning',
    relation: 'emotion_to_recovery',
    themes: ['emotion_recovery'],
    requiredClaims: ['recovery'],
    blockedClaims: ['emotion_regulation_growth'],
    pattern: '{topic} 마음을 표현한 뒤 다시 놀이 흐름으로 돌아왔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['safe', 'specific'],
  },
  {
    id: 'compare_sort_01',
    section: 'learning',
    relation: 'single_event',
    themes: ['compare'],
    requiredClaims: ['compare'],
    blockedClaims: ['math_ability_growth'],
    pattern: '{topic} 자신이 정한 기준에 따라 비교하거나 나누어 보았다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['natural', 'safe'],
  },
  {
    id: 'support_retry_01',
    section: 'support',
    relation: 'retry_after_setback',
    themes: ['retry'],
    requiredClaims: ['retry'],
    blockedClaims: ['support_done'],
    pattern: '다음에는 다시 시도해 볼 시간을 먼저 두고, 필요한 경우 재료의 위치나 수량을 조정해 본다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_explore_01',
    section: 'support',
    relation: 'action_to_material_exploration',
    themes: ['change_explore', 'question', 'compare'],
    requiredClaims: ['explore'],
    blockedClaims: ['support_done'],
    pattern: '관찰한 전후 모습이나 차이를 비교해 볼 수 있는 자료를 가까이에 둔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_make_01',
    section: 'support',
    relation: 'action_to_material_exploration',
    themes: ['make'],
    requiredClaims: ['make'],
    blockedClaims: ['support_done'],
    pattern: '현재 사용한 재료와 연결되는 다른 재료를 한두 가지 더 마련해 구성 흐름을 이어 본다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_language_01',
    section: 'support',
    relation: 'action_to_expression',
    themes: ['language', 'question', 'story'],
    requiredClaims: ['speech'],
    blockedClaims: ['support_done'],
    pattern: '아이가 말한 내용을 짧게 되짚고, 다음 표현으로 이어질 시간을 둔다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_peer_01',
    section: 'support',
    relation: 'action_to_peer_interaction',
    themes: ['peer_share', 'peer_help', 'rules'],
    requiredClaims: ['peer'],
    blockedClaims: ['support_done'],
    pattern: '함께 사용하는 자료와 차례를 짧게 확인해 주고받는 흐름을 이어 본다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_conflict_01',
    section: 'support',
    relation: 'conflict_to_apology',
    themes: ['conflict'],
    requiredClaims: ['conflict'],
    blockedClaims: ['support_done'],
    pattern: '서로의 말과 행동을 짧게 확인한 뒤 원하는 것을 말로 표현할 수 있도록 돕는다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_emotion_01',
    section: 'support',
    relation: 'single_event',
    themes: ['emotion_expression'],
    requiredClaims: ['emotion_expression'],
    blockedClaims: ['recovery_claim', 'support_done'],
    pattern: '표현을 재촉하지 않고 머물 수 있는 자리를 마련해 말과 행동을 더 살펴본다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['conservative', 'safe'],
  },
  {
    id: 'support_recovery_01',
    section: 'support',
    relation: 'emotion_to_recovery',
    themes: ['emotion_recovery'],
    requiredClaims: ['recovery'],
    blockedClaims: ['support_done'],
    pattern: '다시 시작하는 속도를 기다리며 이전 놀이 흐름과 자연스럽게 연결한다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_selfhelp_01',
    section: 'support',
    relation: 'action_to_self_care',
    themes: ['selfhelp'],
    requiredClaims: ['self_care'],
    blockedClaims: ['support_done'],
    pattern: '스스로 해 볼 시간을 먼저 두고 필요한 단계에서만 짧게 도와준다.',
    tone: 'teacher_record',
    length: 'short',
    qualityTags: ['specific', 'future', 'safe'],
  },
  {
    id: 'support_movement_01',
    section: 'support',
    relation: 'single_event',
    themes: ['movement'],
    requiredClaims: ['movement'],
    blockedClaims: ['support_done'],
    pattern: '같은 움직임을 안전하게 반복해 볼 수 있도록 충분한 공간을 확보한다.',
    tone: 'teacher_record',
    length: 'medium',
    qualityTags: ['specific', 'future', 'safe'],
  },
];

export function getApprovedPhraseBank({ section, primaryTheme, secondaryTheme, relation }) {
  const themes = [primaryTheme, secondaryTheme].filter(Boolean);
  return APPROVED_PHRASE_BANK.filter((item) => item.section === section)
    .filter((item) => !item.relation || item.relation === relation || item.relation === 'single_event' || relation === 'single_event')
    .filter((item) => !item.themes?.length || item.themes.some((theme) => themes.includes(theme)));
}

const CONTRAST_THEME_DEFINITIONS = [
  { theme: 'retry', meaning: '뜻대로 되지 않아도 다시 시도함', preferPattern: '{child}은/는 뜻대로 되지 않는 순간에도 다시 시도하며 놀이를 이어 갔다.' },
  { theme: 'change_explore', meaning: '대상이나 변화에 관심을 두고 탐색함', preferPattern: '{child}은/는 관찰한 변화에 관심을 두고 대상의 특징을 살펴보았다.' },
  { theme: 'make', meaning: '재료를 사용해 형태를 구성함', preferPattern: '{child}은/는 재료를 조합하며 자신이 생각한 형태를 구성해 보았다.' },
  { theme: 'language', meaning: '생각이나 경험을 말로 표현함', preferPattern: '{child}은/는 관찰한 내용이나 생각을 말로 표현하며 활동을 이어 갔다.' },
  { theme: 'peer_share', meaning: '친구와 함께 사용하거나 역할을 나눔', preferPattern: '{child}은/는 친구와 함께 사용하는 흐름 안에서 자신의 차례와 역할을 경험하였다.' },
  { theme: 'conflict', meaning: '갈등 상황에서 말이나 행동으로 조정함', preferPattern: '{child}은/는 갈등 상황에서 자신의 요구를 표현하며 상황을 조정해 보았다.' },
  { theme: 'rules', meaning: '차례나 정해진 순서를 기다림', preferPattern: '{child}은/는 정해진 순서를 확인하며 차례를 기다리는 경험을 하였다.' },
  { theme: 'selfhelp', meaning: '일상생활 행동을 스스로 시도함', preferPattern: '{child}은/는 일상생활에서 필요한 행동을 스스로 시도해 보았다.' },
  { theme: 'movement', meaning: '몸의 움직임과 방향을 조절함', preferPattern: '{child}은/는 움직임의 속도와 방향을 조절하며 활동에 참여하였다.' },
  { theme: 'emotion_expression', meaning: '관찰된 말이나 행동으로 마음을 표현함', preferPattern: '{child}은/는 관찰된 말과 행동으로 현재의 마음을 표현하였다.' },
  { theme: 'emotion_recovery', meaning: '표현 뒤 다시 활동 흐름으로 돌아옴', preferPattern: '{child}은/는 마음을 표현한 뒤 다시 활동의 흐름으로 돌아왔다.' },
  { theme: 'roleplay', meaning: '역할에 맞는 말과 행동으로 놀이를 이어 감', preferPattern: '{child}은/는 맡은 역할에 맞는 말과 행동으로 놀이 장면을 이어 갔다.' },
  { theme: 'compare', meaning: '기준에 따라 비교하거나 나눔', preferPattern: '{child}은/는 자신이 정한 기준에 따라 대상을 비교하거나 나누어 보았다.' },
  { theme: 'peer_help', meaning: '도움 요청이나 도움 주기를 말과 행동으로 주고받음', preferPattern: '{child}은/는 필요한 도움을 말이나 행동으로 주고받으며 놀이를 이어 갔다.' },
];

const CONTRAST_RULE_TEMPLATES = [
  {
    id: 'reject_development_claim',
    rejectPattern: '{child}은/는 활동을 통해 발달과 능력이 향상되었다.',
    rejectReason: 'unsupported_development_claim',
    preferReason: 'keeps_observed_action_without_development_claim',
  },
  {
    id: 'reject_too_generic',
    rejectPattern: '{child}은/는 다양한 경험을 통해 성장하는 모습을 보였다.',
    rejectReason: 'too_generic_without_scene_link',
    preferReason: 'specific_safe_teacher_style',
  },
  {
    id: 'reject_report_style',
    rejectPattern: '{child}은/는 해당 활동을 경험하며 긍정적인 태도를 형성하였다.',
    rejectReason: 'report_like_evaluation_style',
    preferReason: 'teacher_record_ending',
  },
  {
    id: 'reject_overlong',
    rejectPattern: '{child}은/는 여러 상황 속에서 다양한 행동과 생각을 함께 표현하며 놀이와 관계와 탐색을 동시에 이어 갔다.',
    rejectReason: 'too_many_meanings_one_sentence',
    preferReason: 'one_core_meaning',
  },
  {
    id: 'reject_observation_repeat',
    rejectPattern: '{child}은/는 관찰내용에 쓰인 행동을 그대로 반복하여 다시 설명하였다.',
    rejectReason: 'repeats_observation',
    preferReason: 'better_section_separation',
  },
  {
    id: 'reject_abstract_support',
    rejectPattern: '다양한 경험을 제공하고 지속적으로 격려한다.',
    rejectReason: 'abstract_support_plan',
    preferReason: 'support_linked_to_observed_flow',
  },
  {
    id: 'reject_purpose_repeat',
    rejectPattern: '{child}이/가 표현할 수 있도록 다양한 경험을 할 수 있도록 지원한다.',
    rejectReason: 'repeated_purpose_connector',
    preferReason: 'clean_connector',
  },
  {
    id: 'prefer_teacher_record',
    rejectPattern: '{child}은/는 매우 훌륭하게 활동하며 긍정적인 성장을 보였다.',
    rejectReason: 'overstated_teacher_praise',
    preferReason: 'warm_without_overclaim',
  },
];

export const CONTRAST_SETS = CONTRAST_THEME_DEFINITIONS.flatMap((definition) =>
  CONTRAST_RULE_TEMPLATES.map((template, index) => ({
    id: `${definition.theme}_contrast_${String(index + 1).padStart(2, '0')}`,
    theme: definition.theme,
    meaning: definition.meaning,
    candidates: [
      {
        id: template.id,
        textPattern: template.rejectPattern,
        quality: 'reject',
        reason: template.rejectReason,
      },
      {
        id: 'teacher_record',
        textPattern: definition.preferPattern,
        quality: 'prefer',
        reason: template.preferReason,
      },
    ],
    rules: {
      prefer: [template.preferReason, 'fact_bound', 'teacher_record'],
      reject: [template.rejectReason],
    },
    metadataOnly: true,
  })));

export default APPROVED_PHRASE_BANK;
