// B2 themes are declarative. Generation logic must not add claims outside these definitions.
const support = (id, text) => ({ id, text });

export const B2_THEMES = [
  { id: 'retry', priority: 100, trigger: /(다시|재시도|여러 번|계속|무너지|안 되|실패|고쳐)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['peer_help', 'language'], conflictThemes: [], allowedClaims: ['다시 시도함', '방법을 바꾸어 이어 감'], blockedClaims: ['자신감 향상', '문제해결력 발달'], allowedSupportActions: [support('retry_material', '비슷한 시도를 이어 갈 수 있도록 크기와 형태가 다른 재료를 곁에 마련한다.'), support('retry_time', '스스로 방법을 바꾸어 볼 수 있도록 충분한 시간을 두고 기다린다.')], phraseFamilies: ['retry_process', 'retry_sequence', 'retry_action'], fallbackPolicy: 'safe', testCases: ['탑이 무너지자 다시 쌓았다'] },
  { id: 'change_explore', priority: 95, trigger: /(섞|녹|얼|변하|달라|관찰|살펴|돋보기|들여다보|지켜보)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['question', 'compare'], conflictThemes: [], allowedClaims: ['변화를 살핌', '대상을 자세히 관찰함'], blockedClaims: ['원리를 이해함', '관찰력이 뛰어남'], allowedSupportActions: [support('explore_tools', '관찰을 이어 갈 수 있도록 돋보기와 비교 자료를 가까이에 둔다.'), support('explore_compare', '변화 전후를 나란히 살펴볼 수 있도록 재료를 남겨 둔다.')], phraseFamilies: ['explore_detail', 'explore_change', 'explore_process'], fallbackPolicy: 'safe', testCases: ['돋보기로 잎을 살펴보았다'] },
  { id: 'make', priority: 80, trigger: /(만들|쌓|그리|그렸|접|붙|오리|점토|물감|색칠|꾸미)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['language', 'retry'], conflictThemes: [], allowedClaims: ['재료를 다루어 구성함', '형태로 표현함'], blockedClaims: ['창의력이 뛰어남', '완성도가 높음'], allowedSupportActions: [support('make_materials', '현재 사용한 재료와 연결되는 다른 재료를 한두 가지 더 마련한다.'), support('make_display', '만든 것을 놀이 공간에 남겨 다음 구성으로 이어 갈 수 있게 한다.')], phraseFamilies: ['make_material', 'make_form', 'make_process'], fallbackPolicy: 'safe', testCases: ['점토로 그릇을 만들었다'] },
  { id: 'question', priority: 92, trigger: /(왜|어디|어떻게|물었|물어|질문|궁금)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['change_explore', 'language'], conflictThemes: [], allowedClaims: ['궁금한 점을 질문함'], blockedClaims: ['탐구력이 뛰어남', '원인을 이해함'], allowedSupportActions: [support('question_record', '아이의 질문을 짧게 기록해 두었다가 관련 자료와 함께 놀이로 되돌려 준다.'), support('question_search', '질문에 바로 답하기보다 함께 확인할 수 있는 자료를 마련한다.')], phraseFamilies: ['question_words', 'question_flow', 'question_object'], fallbackPolicy: 'safe', testCases: ['왜 색이 변했냐고 물었다'] },
  { id: 'language', priority: 70, trigger: /("[^"]+"|말하|설명|이야기|불렀|표현)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['story', 'make'], conflictThemes: [], allowedClaims: ['말로 생각을 표현함', '경험을 설명함'], blockedClaims: ['표현력 향상', '언어 발달'], allowedSupportActions: [support('language_echo', '아이의 말을 짧게 되돌려 주고 이어지는 생각을 말할 시간을 둔다.'), support('language_record', '말한 내용을 그림이나 짧은 기록으로 남겨 다음 표현으로 이어지게 한다.')], phraseFamilies: ['language_quote', 'language_explain', 'language_flow'], fallbackPolicy: 'safe', testCases: ['"내가 만들었어"라고 설명했다'] },
  { id: 'roleplay', priority: 85, trigger: /(역할놀이|역할을 맡|의사|손님|주인|엄마 역할|아빠 역할|인 척|병원놀이|가게놀이)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['language', 'peer_share'], conflictThemes: [], allowedClaims: ['역할을 정해 상황을 표현함'], blockedClaims: ['상상력이 풍부함', '리더십'], allowedSupportActions: [support('role_props', '현재 역할과 연결되는 소품을 한두 가지 더해 이야기 흐름이 이어지게 한다.'), support('role_entry', '놀이 흐름을 해치지 않는 짧은 역할로 참여해 다음 장면을 열어 준다.')], phraseFamilies: ['role_scene', 'role_words', 'role_flow'], fallbackPolicy: 'safe', testCases: ['의사 역할을 맡아 진료했다'] },
  { id: 'peer_share', priority: 88, trigger: /(친구|또래).{0,20}(함께|같이|나눠|건네|빌려|번갈아|양보)|(함께|같이|나눠|건네|빌려|번갈아|양보).{0,20}(친구|또래)/, requiredEvidence: /친구|또래/, excludedEvidence: null, coexistThemes: ['language', 'peer_help'], conflictThemes: ['conflict'], allowedClaims: ['친구와 나누거나 함께함'], blockedClaims: ['사회성 발달', '배려심이 뛰어남'], allowedSupportActions: [support('peer_roles', '역할과 순서를 정해 볼 수 있는 공동 놀이를 이어서 마련한다.'), support('peer_materials', '함께 사용하기 좋은 재료를 충분히 두어 주고받는 흐름이 이어지게 한다.')], phraseFamilies: ['peer_action', 'peer_flow', 'peer_words'], fallbackPolicy: 'safe', testCases: ['친구에게 가위를 건네주었다'] },
  { id: 'conflict', priority: 110, trigger: /(다투|싸우|잡아당|밀|빼앗|미안|사과|화해|부딪)/, requiredEvidence: /친구|또래|미안|사과/, excludedEvidence: null, coexistThemes: ['language'], conflictThemes: ['peer_share'], allowedClaims: ['갈등 상황에서 말이나 행동으로 관계를 조정함'], blockedClaims: ['갈등이 해결됨', '사회성 발달', '배려심'], allowedSupportActions: [support('conflict_words', '서로의 행동과 말을 차례로 짚어 보며 원하는 것을 짧게 표현하도록 돕는다.'), support('conflict_restart', '각자의 마음을 말한 뒤 놀이를 다시 시작할 수 있는 자리를 마련한다.')], phraseFamilies: ['conflict_words', 'conflict_sequence', 'conflict_action'], fallbackPolicy: 'safe', testCases: ['친구와 다툰 뒤 미안하다고 말했다'] },
  { id: 'rules', priority: 90, trigger: /(차례|순서|규칙|줄을 서|기다렸|기다렸다|새치기)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['peer_share'], conflictThemes: [], allowedClaims: ['차례나 순서를 지킴'], blockedClaims: ['준법성', '사회성 발달'], allowedSupportActions: [support('rules_turn', '차례를 눈으로 확인할 수 있는 표시를 두어 기다림의 흐름을 이어 준다.'), support('rules_repeat', '같은 순서를 반복해 경험할 수 있는 짧은 순환 놀이를 마련한다.')], phraseFamilies: ['rules_action', 'rules_sequence', 'rules_flow'], fallbackPolicy: 'safe', testCases: ['차례를 기다렸다가 탔다'] },
  { id: 'selfhelp', priority: 75, trigger: /(스스로|혼자|정리|치우|이불|신발|옷을|지퍼|화장실|손을 씻|양치|식판|급식|식사|채소|한 입 먹)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: [], conflictThemes: [], allowedClaims: ['일상 행동을 스스로 해 봄'], blockedClaims: ['자립심 완성', '습관이 확립됨'], allowedSupportActions: [support('selfhelp_wait', '스스로 해 보는 시간을 먼저 두고 필요한 단계에서만 짧게 돕는다.'), support('selfhelp_cue', '행동 순서를 스스로 확인할 수 있는 간단한 단서를 가까이에 둔다.')], phraseFamilies: ['selfhelp_action', 'selfhelp_sequence', 'selfhelp_flow'], fallbackPolicy: 'safe', testCases: ['식판을 스스로 정리했다'] },
  { id: 'movement', priority: 72, trigger: /(뛰|달리|점프|평균대|균형|던지|공을|기어|그네|한 발|미끄럼틀|페달)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['retry'], conflictThemes: [], allowedClaims: ['힘과 방향을 조절해 움직임'], blockedClaims: ['운동 능력이 뛰어남', '대근육 발달'], allowedSupportActions: [support('movement_levels', '높이와 거리가 다른 움직임 선택지를 마련해 스스로 난이도를 고르게 한다.'), support('movement_space', '같은 움직임을 안전하게 반복할 수 있도록 충분한 공간을 확보한다.')], phraseFamilies: ['movement_control', 'movement_repeat', 'movement_flow'], fallbackPolicy: 'safe', testCases: ['평균대에서 균형을 잡았다'] },
  { id: 'emotion_expression', priority: 105, trigger: /(울|눈물|속상|화나|짜증|무서워|놀랐|아쉬워|기뻐|웃었)/, requiredEvidence: null, excludedEvidence: /(울고 있는|우는) 친구/, coexistThemes: ['language'], conflictThemes: ['emotion_recovery'], allowedClaims: ['관찰된 말·표정·행동으로 마음을 표현함'], blockedClaims: ['정서 조절 능력', '감정을 극복함'], allowedSupportActions: [support('emotion_name', '관찰된 말과 행동을 짧게 되짚어 마음을 표현할 시간을 둔다.'), support('emotion_space', '표현을 재촉하지 않고 편안하게 머물 수 있는 자리를 마련한다.')], phraseFamilies: ['emotion_action', 'emotion_words', 'emotion_observed'], fallbackPolicy: 'minimal', testCases: ['탑이 무너지자 울었다'] },
  { id: 'emotion_recovery', priority: 115, trigger: /(울|눈물|속상|화나|무서워|놀랐).{0,40}(진정|안정을 찾|다시.{0,10}집중|괜찮아)|(진정|안정을 찾).{0,40}(울|속상|놀랐)/, requiredEvidence: /(진정|안정을 찾|다시.{0,10}집중|괜찮아)/, excludedEvidence: null, coexistThemes: [], conflictThemes: ['emotion_expression'], allowedClaims: ['입력에 드러난 회복 행동'], blockedClaims: ['정서 조절 능력 향상', '불안을 극복함'], allowedSupportActions: [support('recovery_routine', '마음이 흔들릴 때 다시 선택할 수 있는 익숙한 놀이와 자리를 가까이에 둔다.'), support('recovery_pace', '아이의 회복 속도를 기다리며 다시 시작한 행동을 짧게 짚어 준다.')], phraseFamilies: ['recovery_sequence', 'recovery_action', 'recovery_flow'], fallbackPolicy: 'minimal', testCases: ['울었지만 곧 진정하고 다시 놀이했다'] },
  { id: 'compare', priority: 82, trigger: /(분류|나누어|크기 순|순서대로|비교|더 크|더 작|같은 것|다른 것|짝을 맞)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['change_explore'], conflictThemes: [], allowedClaims: ['기준에 따라 비교·분류·배열함'], blockedClaims: ['논리력이 뛰어남', '수 개념 발달'], allowedSupportActions: [support('compare_set', '크기와 모양이 다른 자료를 더해 같은 기준으로 비교를 이어 가게 한다.'), support('compare_words', '아이가 사용한 비교 기준을 말로 되돌려 주고 다른 기준도 살펴보게 한다.')], phraseFamilies: ['compare_basis', 'compare_action', 'compare_flow'], fallbackPolicy: 'safe', testCases: ['잎을 크기 순서대로 놓았다'] },
  { id: 'story', priority: 78, trigger: /(이야기를 만들|다음에는|그러고 나서|그 다음|옛날에|라고 하며.{0,20}이어|처음.{0,30}마지막)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['language', 'roleplay'], conflictThemes: [], allowedClaims: ['사건이나 말을 순서 있게 이어 감'], blockedClaims: ['서사 능력 발달', '상상력이 뛰어남'], allowedSupportActions: [support('story_record', '이어진 이야기를 그림이나 사진 순서로 남겨 다음 장면을 덧붙이게 한다.'), support('story_prompt', '아이의 마지막 말을 되돌려 주고 다음 장면을 기다린다.')], phraseFamilies: ['story_sequence', 'story_words', 'story_flow'], fallbackPolicy: 'safe', testCases: ['그 다음에는 배가 출발한다고 이야기를 이었다'] },
  { id: 'peer_help', priority: 86, trigger: /(도와|도움.{0,8}(요청|청하)|잡아 줘|해 줘|건네주|알려 주)/, requiredEvidence: null, excludedEvidence: null, coexistThemes: ['peer_share', 'language'], conflictThemes: [], allowedClaims: ['도움을 요청하거나 행동으로 도움을 줌'], blockedClaims: ['배려심이 뛰어남', '협동심 발달'], allowedSupportActions: [support('help_words', '도움이 필요한 순간 사용할 수 있는 짧은 말을 놀이 속에서 함께 확인한다.'), support('help_roles', '서로 도움을 주고받을 수 있는 역할이 있는 놀이를 마련한다.')], phraseFamilies: ['help_action', 'help_words', 'help_flow'], fallbackPolicy: 'safe', testCases: ['친구에게 여기를 잡아 달라고 말했다'] },
];

export const B2_THEME_BY_ID = Object.fromEntries(B2_THEMES.map((theme) => [theme.id, theme]));
